// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gofast-pkg/csv"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCSV creates a new instance of MockCSV. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCSV(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCSV {
	mock := &MockCSV{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCSV is an autogenerated mock type for the CSV type
type MockCSV struct {
	mock.Mock
}

type MockCSV_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCSV) EXPECT() *MockCSV_Expecter {
	return &MockCSV_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockCSV
func (_mock *MockCSV) Decode(obj any) (csv.Warning, error) {
	ret := _mock.Called(obj)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 csv.Warning
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) (csv.Warning, error)); ok {
		return returnFunc(obj)
	}
	if returnFunc, ok := ret.Get(0).(func(any) csv.Warning); ok {
		r0 = returnFunc(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(csv.Warning)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(obj)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCSV_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockCSV_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - obj any
func (_e *MockCSV_Expecter) Decode(obj interface{}) *MockCSV_Decode_Call {
	return &MockCSV_Decode_Call{Call: _e.mock.On("Decode", obj)}
}

func (_c *MockCSV_Decode_Call) Run(run func(obj any)) *MockCSV_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCSV_Decode_Call) Return(warning csv.Warning, err error) *MockCSV_Decode_Call {
	_c.Call.Return(warning, err)
	return _c
}

func (_c *MockCSV_Decode_Call) RunAndReturn(run func(obj any) (csv.Warning, error)) *MockCSV_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// DecodeWithDecoder provides a mock function for the type MockCSV
func (_mock *MockCSV) DecodeWithDecoder(d csv.Decoder) error {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for DecodeWithDecoder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(csv.Decoder) error); ok {
		r0 = returnFunc(d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCSV_DecodeWithDecoder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeWithDecoder'
type MockCSV_DecodeWithDecoder_Call struct {
	*mock.Call
}

// DecodeWithDecoder is a helper method to define mock.On call
//   - d csv.Decoder
func (_e *MockCSV_Expecter) DecodeWithDecoder(d interface{}) *MockCSV_DecodeWithDecoder_Call {
	return &MockCSV_DecodeWithDecoder_Call{Call: _e.mock.On("DecodeWithDecoder", d)}
}

func (_c *MockCSV_DecodeWithDecoder_Call) Run(run func(d csv.Decoder)) *MockCSV_DecodeWithDecoder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 csv.Decoder
		if args[0] != nil {
			arg0 = args[0].(csv.Decoder)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCSV_DecodeWithDecoder_Call) Return(err error) *MockCSV_DecodeWithDecoder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCSV_DecodeWithDecoder_Call) RunAndReturn(run func(d csv.Decoder) error) *MockCSV_DecodeWithDecoder_Call {
	_c.Call.Return(run)
	return _c
}
