// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gofast-pkg/csv"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDecoder creates a new instance of MockDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDecoder {
	mock := &MockDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDecoder is an autogenerated mock type for the Decoder type
type MockDecoder struct {
	mock.Mock
}

type MockDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDecoder) EXPECT() *MockDecoder_Expecter {
	return &MockDecoder_Expecter{mock: &_m.Mock}
}

// ContextGet provides a mock function for the type MockDecoder
func (_mock *MockDecoder) ContextGet(key string) (any, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ContextGet")
	}

	var r0 any
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (any, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockDecoder_ContextGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContextGet'
type MockDecoder_ContextGet_Call struct {
	*mock.Call
}

// ContextGet is a helper method to define mock.On call
//   - key string
func (_e *MockDecoder_Expecter) ContextGet(key interface{}) *MockDecoder_ContextGet_Call {
	return &MockDecoder_ContextGet_Call{Call: _e.mock.On("ContextGet", key)}
}

func (_c *MockDecoder_ContextGet_Call) Run(run func(key string)) *MockDecoder_ContextGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDecoder_ContextGet_Call) Return(value any, found bool) *MockDecoder_ContextGet_Call {
	_c.Call.Return(value, found)
	return _c
}

func (_c *MockDecoder_ContextGet_Call) RunAndReturn(run func(key string) (any, bool)) *MockDecoder_ContextGet_Call {
	_c.Call.Return(run)
	return _c
}

// ContextSet provides a mock function for the type MockDecoder
func (_mock *MockDecoder) ContextSet(key string, value any) {
	_mock.Called(key, value)
	return
}

// MockDecoder_ContextSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContextSet'
type MockDecoder_ContextSet_Call struct {
	*mock.Call
}

// ContextSet is a helper method to define mock.On call
//   - key string
//   - value any
func (_e *MockDecoder_Expecter) ContextSet(key interface{}, value interface{}) *MockDecoder_ContextSet_Call {
	return &MockDecoder_ContextSet_Call{Call: _e.mock.On("ContextSet", key, value)}
}

func (_c *MockDecoder_ContextSet_Call) Run(run func(key string, value any)) *MockDecoder_ContextSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDecoder_ContextSet_Call) Return() *MockDecoder_ContextSet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDecoder_ContextSet_Call) RunAndReturn(run func(key string, value any)) *MockDecoder_ContextSet_Call {
	_c.Run(run)
	return _c
}

// newInstance provides a mock function for the type MockDecoder
func (_mock *MockDecoder) newInstance() (any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for newInstance")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDecoder_newInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'newInstance'
type MockDecoder_newInstance_Call struct {
	*mock.Call
}

// newInstance is a helper method to define mock.On call
func (_e *MockDecoder_Expecter) newInstance() *MockDecoder_newInstance_Call {
	return &MockDecoder_newInstance_Call{Call: _e.mock.On("newInstance")}
}

func (_c *MockDecoder_newInstance_Call) Run(run func()) *MockDecoder_newInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDecoder_newInstance_Call) Return(v any, err error) *MockDecoder_newInstance_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDecoder_newInstance_Call) RunAndReturn(run func() (any, error)) *MockDecoder_newInstance_Call {
	_c.Call.Return(run)
	return _c
}

// saveInstance provides a mock function for the type MockDecoder
func (_mock *MockDecoder) saveInstance(v any) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for saveInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDecoder_saveInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'saveInstance'
type MockDecoder_saveInstance_Call struct {
	*mock.Call
}

// saveInstance is a helper method to define mock.On call
//   - v any
func (_e *MockDecoder_Expecter) saveInstance(v interface{}) *MockDecoder_saveInstance_Call {
	return &MockDecoder_saveInstance_Call{Call: _e.mock.On("saveInstance", v)}
}

func (_c *MockDecoder_saveInstance_Call) Run(run func(v any)) *MockDecoder_saveInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDecoder_saveInstance_Call) Return(err error) *MockDecoder_saveInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDecoder_saveInstance_Call) RunAndReturn(run func(v any) error) *MockDecoder_saveInstance_Call {
	_c.Call.Return(run)
	return _c
}

// warningUnusedField provides a mock function for the type MockDecoder
func (_mock *MockDecoder) warningUnusedField(warn csv.Warning) error {
	ret := _mock.Called(warn)

	if len(ret) == 0 {
		panic("no return value specified for warningUnusedField")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(csv.Warning) error); ok {
		r0 = returnFunc(warn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDecoder_warningUnusedField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'warningUnusedField'
type MockDecoder_warningUnusedField_Call struct {
	*mock.Call
}

// warningUnusedField is a helper method to define mock.On call
//   - warn csv.Warning
func (_e *MockDecoder_Expecter) warningUnusedField(warn interface{}) *MockDecoder_warningUnusedField_Call {
	return &MockDecoder_warningUnusedField_Call{Call: _e.mock.On("warningUnusedField", warn)}
}

func (_c *MockDecoder_warningUnusedField_Call) Run(run func(warn csv.Warning)) *MockDecoder_warningUnusedField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 csv.Warning
		if args[0] != nil {
			arg0 = args[0].(csv.Warning)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDecoder_warningUnusedField_Call) Return(err error) *MockDecoder_warningUnusedField_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDecoder_warningUnusedField_Call) RunAndReturn(run func(warn csv.Warning) error) *MockDecoder_warningUnusedField_Call {
	_c.Call.Return(run)
	return _c
}
